import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from "./utils/providers";

import SigninSignoutButton from "./components/SigninSignoutButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <main className="flex h-screen flex-col items-center p-24">
            <div className="z-10 max-w-5xl w-full items-center justify-between  lg:flex">
              <div></div>
              <SigninSignoutButton />
            </div>

            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
